mysql:
  host: localhost
  user: root
  database: souls
  password: root1
SPEED: # name souls
  price: 250 # price to buy
  upgrade_price: 50 # only
FORCE:
  price: 250
  upgrade_price: 50
FIRE_RESISTANCE:
  price: 250
  upgrade_price: 50
JUMP:
  price: 250
  upgrade_price: 50
FAST_DIGGING:
  price: 250
  upgrade_price: 50
RESISTANCE:
  price: 250
  upgrade_price: 50
REGENERATION:
  price: 250
  upgrade_price: 50
NIGHT_VISION:
  price: 250
  upgrade_price: 50
